class ScoreboardController < ApplicationController
  def index
    @props = { scores: [{:Player=>"fyodor dostoevsky", :gamez=>"PuzzleMania", :skore=>91976},
 {:Player=>"meryl streep", :gamez=>"Shoot Em Up", :skore=>43209},
 {:Player=>"fyodor dostoevsky", :gamez=>"Coin Collector", :skore=>77543},
 {:Player=>"fyodor dostoevsky", :gamez=>"Shoot Em Up", :skore=>11767},
 {:Player=>"john doe", :gamez=>"Coin Collector", :skore=>69593},
 {:Player=>"john doe", :gamez=>"Coin Collector", :skore=>92291},
 {:Player=>"meryl streep", :gamez=>"PuzzleMania", :skore=>91887},
 {:Player=>"meryl streep", :gamez=>"Coin Collector", :skore=>43809},
 {:Player=>"fyodor dostoevsky", :gamez=>"Shoot Em Up", :skore=>23044},
 {:Player=>"john doe", :gamez=>"PuzzleMania", :skore=>46448},
 {:Player=>"john doe", :gamez=>"PuzzleMania", :skore=>74586},
 {:Player=>"bib fortuna", :gamez=>"Shoot Em Up", :skore=>43823},
 {:Player=>"bib fortuna", :gamez=>"Coin Collector", :skore=>65974},
 {:Player=>"fyodor dostoevsky", :gamez=>"PuzzleMania", :skore=>72600},
 {:Player=>"fyodor dostoevsky", :gamez=>"Shoot Em Up", :skore=>15326},
 {:Player=>"john doe", :gamez=>"Shoot Em Up", :skore=>56147},
 {:Player=>"fyodor dostoevsky", :gamez=>"Coin Collector", :skore=>60457},
 {:Player=>"meryl streep", :gamez=>"Shoot Em Up", :skore=>26818},
 {:Player=>"bib fortuna", :gamez=>"Coin Collector", :skore=>69347},
 {:Player=>"bib fortuna", :gamez=>"PuzzleMania", :skore=>92009},
 {:Player=>"meryl streep", :gamez=>"PuzzleMania", :skore=>83928},
 {:Player=>"fyodor dostoevsky", :gamez=>"PuzzleMania", :skore=>2588},
 {:Player=>"meryl streep", :gamez=>"PuzzleMania", :skore=>15697},
 {:Player=>"bib fortuna", :gamez=>"Coin Collector", :skore=>20550},
 {:Player=>"meryl streep", :gamez=>"PuzzleMania", :skore=>39360},
 {:Player=>"fyodor dostoevsky", :gamez=>"Coin Collector", :skore=>1974},
 {:Player=>"bib fortuna", :gamez=>"Shoot Em Up", :skore=>93436},
 {:Player=>"john doe", :gamez=>"Coin Collector", :skore=>51195},
 {:Player=>"bib fortuna", :gamez=>"Coin Collector", :skore=>86938},
 {:Player=>"john doe", :gamez=>"PuzzleMania", :skore=>21977},
 {:Player=>"meryl streep", :gamez=>"PuzzleMania", :skore=>4063},
 {:Player=>"meryl streep", :gamez=>"PuzzleMania", :skore=>1234},
 {:Player=>"john doe", :gamez=>"Coin Collector", :skore=>71957},
 {:Player=>"john doe", :gamez=>"Shoot Em Up", :skore=>55737},
 {:Player=>"fyodor dostoevsky", :gamez=>"Coin Collector", :skore=>4679},
 {:Player=>"bib fortuna", :gamez=>"Shoot Em Up", :skore=>34419},
 {:Player=>"meryl streep", :gamez=>"PuzzleMania", :skore=>58139},
 {:Player=>"bib fortuna", :gamez=>"Shoot Em Up", :skore=>74728},
 {:Player=>"john doe", :gamez=>"Coin Collector", :skore=>51232},
 {:Player=>"meryl streep", :gamez=>"PuzzleMania", :skore=>90222}]}
  end
end
